version: '3.8'

services:
  web:
    image: php:8.2-apache
    container_name: suli_web
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html:Z
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    command: >
      bash -c "docker-php-ext-install mysqli && docker-php-ext-enable mysqli && apache2-foreground"
    depends_on:
      - db

  db:
    image: mariadb:10.6
    container_name: suli_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: iskola
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: suli_pma
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - db

volumes:
  db_data:
